# Generated by Django 2.0 on 2018-06-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='libre',
            field=models.IntegerField(default=0),
        ),
    ]
