# Generated by Django 2.0 on 2018-06-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_asiento_libre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nEntradas', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Sesion')),
            ],
        ),
    ]
